/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mj_jnitest_JNIUtils */

#ifndef _Included_com_mj_jnitest_JNIUtils
#define _Included_com_mj_jnitest_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mj_jnitest_JNIUtils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mj_jnitest_JNIUtils_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_mj_jnitest_JNIUtils
 * Method:    getString2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mj_jnitest_JNIUtils_getString2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
